### ISSUE TITLE
Support for empty DevServerTarget

### ISSUE THREAD

**Issue by ashblox** [ngChile/ngx-devkit-cypress-builder#24]
I could be missing something, but I have tried to define multiple e2e configurations in my project, and I can't seem to figure out how to run my Cypress tests without serving up the local app.

Here is my configuration: 
```
"my-app-e2e": {
            "root": "cypress/",
            "projectType": "application",
            "architect": {
                "e2e": {
                    "builder": "ngx-devkit-cypress-builder:cypress",
                    "options": {
                        "mode": "browser", 
                        "devServerTarget": "my-app:serve"
                    },
                    "configurations": {
                        "ci": {
                            "mode": "console",
                            "baseUrl": "https://dev.mycompany.com/myapp"
                        },
                        "regression": {
                            "mode": "console",
                            "devServerTarget": "",
                            "reporter": "@mycompany/mycompany-cypress-reporter",
                            "baseUrl": "https://dev.mycompany.com/myapp#"
                        },
                        "dev": {
                            "devServerTarget": "",
                            "baseUrl": "https://dev.mycompany.com/myapp#"
                        },
                        "local-local": {
                            "devServerTarget": "my-app:serve:local-proxy",
                            "env": { "sampleServiceUrl": "https://localhost:5141" }
                        },
                        "local-dev": {
                            "mode": "browser", 
                            "devServerTarget": "my-app:serve"
                        }  // same as running e2e
                    }
```

Ultimately, I would like the `regression` and `dev` commands to not serve up the app at all. However, when I run `npm run e2e:regression`, I get an error saying `Invalid target string: ""`. If I remove `devServerTarget` from the e2e options completely, I get this error: `Cannot read property 'split' of undefined`. 

So for now, I've just removed the `devServerTarget` designation completely from these steps, but the CLI is serving up the app for no reason. 

Would you please advise how I can run my tests against an already running application? 

Thank you!

**Comment by gpincheiraa** [comment]
Hi! Can you try using  `@ngchile/cypress-cucumber-schematics:cypress`.

```
  npm install --save-dev @ngchile/cypress-cucumber-schematics
```

Then edit your angular.json file

```
...
   "builder": "@ngchile/cypress-cucumber-schematics:cypress",
```

If you want avoid the execution of `devServerTarget` omit  this configuration and could be work. (this is the code related to this ---> https://github.com/ngChile/ngchile-packages/blob/master/packages/cypress-cucumber-schematics/src/builders/cypress/index.ts#L45-L47

**Comment by ashblox** [comment]
It might be worth mentioning that I had to remove the `:cypress` from the npm install step. But the other builder worked like a charm! Thank you!
